version: "3.8"

services:
  # Production application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: forge-ui-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - forge-network

  # Development service with hot reloading
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    container_name: forge-ui-dev
    restart: unless-stopped
    # Don't expose port directly - Nginx will handle this
    expose:
      - "5173"
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./react-router.config.ts:/app/react-router.config.ts
      # Exclude node_modules from volume to use the container's node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    command: pnpm dev
    networks:
      - forge-network
    # Add container hostname for internal reference
    hostname: forge-ui-dev
    # Make sure Nginx can resolve the hostname
    extra_hosts:
      - "forge-ui.kbra.vm:127.0.0.1"

  # Nginx reverse proxy for custom hostname access (development)
  nginx:
    image: nginx:alpine
    container_name: forge-ui-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/forge-ui.conf:/etc/nginx/conf.d/default.conf
      # Create log directory if needed
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - dev
    networks:
      - forge-network
    # Allow Nginx to use the custom hostname
    extra_hosts:
      - "forge-ui.kbra.vm:127.0.0.1"
    # Use Docker's internal DNS for service discovery instead of extra_hosts

  # Nginx production service
  nginx-prod:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: forge-ui-nginx-prod
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - forge-network
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "forge-ui.kbra.vm:127.0.0.1"

# Define networks
networks:
  forge-network:
    driver: bridge