#!/bin/sh

# Find CSS and JS files
CSS_FILE=$(find /usr/share/nginx/html/assets -name "root-*.css" | xargs basename 2>/dev/null | head -1)
JS_FILE=$(find /usr/share/nginx/html/assets -name "entry.client-*.js" | xargs basename 2>/dev/null | head -1)

# Update index.html with the correct paths
if [ -n "$CSS_FILE" ]; then
    sed -i "s/root-[^\"]*\.css/$CSS_FILE/g" /usr/share/nginx/html/index.html
fi

if [ -n "$JS_FILE" ]; then
    sed -i "s/entry\.client-[^\"]*\.js/$JS_FILE/g" /usr/share/nginx/html/index.html
fi

# Add a note that the file was auto-generated
sed -i "1s/^/<!-- Auto-generated by update-assets.sh -->\n/" /usr/share/nginx/html/index.html